apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260515-190340-ktnl31b5hzxl-service
spec:
  selector:
    app: enterprise-system-20260515-190340-ktnl31b5hzxl
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
